version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-web
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: shop-db
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: shop_db
      MARIADB_USER: shopuser
      MARIADB_PASSWORD: shoppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shop-pma
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: shopuser
      PMA_PASSWORD: shoppass
    ports:
      - "8081:80"
    depends_on:
      - mariadb

volumes:
  db_data:
